<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
  </PropertyGroup>
  <PropertyGroup Condition="'$(PublishSingleFile)' == 'true'">
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <PropertyGroup Condition="'$(PublishAot)' == 'true'">
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <IlcInstructionSet>native</IlcInstructionSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(PublishReadyToRun)' == 'true'">
    <PublishReadyToRunCrossgen2ExtraArgs>--instruction-set:native</PublishReadyToRunCrossgen2ExtraArgs>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="experiments/**/*.cs" />
    <Content Remove="experiments/**;global.json" />
    <Content Update="appsettings*.json" CopyToPublishDirectory="Never" Condition="'$(PublishSingleFile)' == 'true'" />
    <None Include=".tools/sqlite/lib/libsqlite3.*" Exclude="**/*.json" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
