version: 3

vars:
  BINARY: bin/Release/net9.0/csharp.dll

tasks:
  build:
    cmd: dotnet build --configuration Release
    sources:
      - "**/*.cs*"
      - "appsettings.*"
    generates:
      - "{{.BINARY}}"
  
  start:
    deps:
      - build
    cmds:
      - rm -rf /tmp/benchmark.sock
      - dotnet {{.BINARY}}
