version: 3

includes:
  load: {taskfile: loadgen/Taskfile.yaml, dir: loadgen}
  rust: {taskfile: rust/Taskfile.yaml, dir: rust}
  go: {taskfile: go/Taskfile.yaml, dir: go}
  ocaml: {taskfile: ocaml/Taskfile.yaml, dir: ocaml}
  haskell: {taskfile: haskell/Taskfile.yaml, dir: haskell}
  bun: {taskfile: bun/Taskfile.yaml, dir: bun}

vars:
  GO_MIGRATE: ../../../github/migrate/cmd/migrate/migrate
  MIGRATIONS_DIR: db/migrations
  DB_FILE: db/db.sqlite
  UNIX_SOCKET: /tmp/benchmark.sock

tasks:
  migrate:
    cmds:
      - rm -rf {{.DB_FILE}}*
      - "{{.GO_MIGRATE}} -path {{.MIGRATIONS_DIR}} -database sqlite3://{{.DB_FILE}} up"
    sources:
      - "{{.GO_MIGRATE}}"
      - "{{.MIGRATIONS_DIR}}/**/*"
    generates:
      - "{{.DB_FILE}}"

  openapi:
    vars:
      KDL_FILE: openapi/http.kdl
      JSON_FILE: openapi/http.json
    cmds:
      - rm -f {{.JSON_FILE}}
      - bunx @responsibleapi/cli {{.KDL_FILE}} -o {{.JSON_FILE}}
      - jq '.openapi = "3.0.0"' {{.JSON_FILE}} > {{.JSON_FILE}}.tmp
      - mv {{.JSON_FILE}}.tmp {{.JSON_FILE}}
    sources:
      - "{{.KDL_FILE}}"
      - Taskfile.yaml
    generates:
      - "{{.JSON_FILE}}"

  post:
    deps: [load:build]
    cmd: python3 loadgen/run.py posts --socket {{.UNIX_SOCKET}} {{.CLI_ARGS}}

  echo:
    deps: [load:build]
    cmd: python3 loadgen/run.py echo --socket {{.UNIX_SOCKET}} {{.CLI_ARGS}}

  benchmark:
    deps: [load:build, rust:build, go:build, ocaml:build]
    cmd: python3 loadgen/measure.py {{.CLI_ARGS | default "results/random-json"}}
