[project]
name = "python-blacksheep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "blacksheep>=2.0.7",
    "uvicorn>=0.33.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.3",
]
