version: 3

tasks:
  start:
    - uv run uvicorn hello:app --uds /tmp/benchmark.sock --ws none --no-access-log --no-proxy-headers --no-server-header --no-date-header

  workers:
    - uv run uvicorn hello:app --uds /tmp/benchmark.sock --workers 10 --ws none --no-access-log --no-proxy-headers --no-server-header --no-date-header
