version: 3

vars:
  JAR: build/libs/kotlin-vertx-panama-1.0-all.jar
  UNIX_SOCKET: /tmp/benchmark.sock

tasks:
  jextract:
    vars:
      BINARY: /Users/adelnizamutdinov/downloads/jextract-22/bin/jextract
      SQLITE3_DIR: /opt/homebrew/opt/sqlite3/
      OUT_DIR: gen/main/java/
    cmd: >
      {{.BINARY}} {{.SQLITE3_DIR}}include/sqlite3.h
      -l :{{.SQLITE3_DIR}}lib/libsqlite3.dylib
      --target-package org.sqlite
      --output {{.OUT_DIR}}
    sources:
      - Taskfile.yaml
    generates:
      - "{{.OUT_DIR}}**/*"

  dev:
    deps:
      - jextract
    cmd: ./gradlew run

  build:
    deps:
      - jextract
    cmd: ./gradlew sJ
    sources:
      - src/**/*
      - gen/**/*
      - gradle/**/*
      - "*gradle*"
    generates:
      - "{{.JAR}}"

  start:
    deps:
      - build
    cmd: java -server -XX:+PerfDisableSharedMem --enable-native-access=ALL-UNNAMED -jar {{.JAR}} -Dhttp.socket={{.UNIX_SOCKET}}
