version: 3

tasks:
  jextract:
    vars:
      BINARY: /Users/adelnizamutdinov/downloads/jextract-22/bin/jextract
      SQLITE3_DIR: /opt/homebrew/opt/sqlite3/
      OUT_DIR: gen/main/java/
    cmd: >
      {{.BINARY}} {{.SQLITE3_DIR}}include/sqlite3.h
      -l :{{.SQLITE3_DIR}}lib/libsqlite3.dylib
      --target-package org.sqlite
      --output {{.OUT_DIR}}
    sources:
      - Taskfile.yaml
    generates:
      - "{{.OUT_DIR}}**/*"

  dev:
    deps:
      - jextract
    cmd: ./gradlew run
