version: 3

tasks:
  build:
    cmd: zig build -Doptimize=ReleaseFast
    sources:
      - src/**/*
      - build.zig*
    generates:
      - zig-out/bin/zig

  start:
    deps:
      - build
    cmd: zig-out/bin/zig

  test:
    cmd: zig build test --summary all
    sources:
      - src/**/*
      - build.zig*
    generates:
      - zig-out/bin/zig
