version: 3

tasks:
  start:
    cmd: zig build run
  sources:
    - src/**/*
    - build.zig*
  generates:
    - zig-out/bin/zig

  test:
    cmd: zig build test --summary all
    sources:
      - src/**/*
      - build.zig*
    generates:
      - zig-out/bin/zig
