version: 3

vars:
  BINARY: dist/server
  LOCAL_PORT: 3000
  UNIX_SOCKET: /tmp/bun.sock

tasks:
  openapi:
    cmd: bun responsible ../http.kdl -o openapi.json
    sources:
      - ../http.kdl
      - bun.lockb
    generates:
      - openapi.json

  start:
    deps:
      - openapi
    cmd: bun --watch src/server.ts

  jbuild:
    desc: Single .js
    cmd: bun build --minify --sourcemap src/server.ts --outdir dist/ --external bun:sqlite
    sources:
      - src/**/*
      - bun.lockb
      - tsconfig.json
      - Taskfile.yaml
    generates:
      - dist/server.js

  jstart:
    deps:
      - jbuild
    cmd: bun dist/server.js

  build:
    desc: Single executable
    cmds:
      - bun build --compile --minify --sourcemap src/server.ts --outfile {{.BINARY}}
      - defer: find . -maxdepth 1 -type f -name "*.bun-build" -delete
    sources:
      - src/**/*
      - bun.lockb
      - tsconfig.json
      - Taskfile.yaml
    generates:
      - "{{.BINARY}}"

  bstart:
    deps:
      - build
    cmd: ./{{.BINARY}}

  post:
    cmd: >
      oha http://localhost:3000/posts --no-tui --unix-socket {{.UNIX_SOCKET}} -z 10s -m POST -T 'application/json' -d '{ "content": "bun benchmark", "email": "bun@gmail.com" }'
