version: 3

vars:
  JAR: build/libs/kotlin-1.0-all.jar
  UNIX_SOCKET: /tmp/benchmark.sock
  JAVA: '{{if .JAVA_HOME}}{{.JAVA_HOME}}/bin/java{{else}}java{{end}}'

tasks:
  jextract:
    cmd: ./gradlew generateSqliteBindings

  dev:
    cmd: ./gradlew run

  build:
    run: once
    cmd: ./gradlew shadowJar

  test:
    cmd: ./gradlew test

  start:
    deps:
      - build
    cmd: >
      "{{.JAVA}}" -server -XX:+PerfDisableSharedMem --enable-native-access=ALL-UNNAMED
      -Dhttp.socket={{.UNIX_SOCKET}}
      -jar {{.JAR}}
