version: 3

vars:
  JAR: build/libs/vertx-sqlite-1.0-all.jar
  LOCAL_PORT: 8080
  UNIX_SOCKET: /tmp/benchmark.sock

tasks:
  openapi:
    cmds:
      - bunx @responsibleapi/cli ../openapi/http.kdl -o src/main/resources/openapi.json.tmp
      - jq '.openapi = "3.0.0"' src/main/resources/openapi.json.tmp > src/main/resources/openapi.json
      - rm src/main/resources/openapi.json.tmp
    sources:
      - ../openapi/http.kdl
      - Taskfile.yaml
    generates:
      - src/main/resources/openapi.json

  build:
    deps:
      - openapi
    cmd: ./gradlew sJ
    sources:
      - src/**/*
      - gradle/**/*
      - "*gradle*"
    generates:
      - "{{.JAR}}"

  start:
    deps:
      - build
    cmd: java -server -XX:+PerfDisableSharedMem -Dhttp.socket={{.UNIX_SOCKET}} -jar {{.JAR}}
